service:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 8080:8080

  web:
    image: amancevice/superset
    restart: always
    ports:
      - 8088:8088